import { ProjectType } from "interfaces/projects";

export const categories = [
    {
        id: 1,
        name: "designAndPrototyping",
        translationObjectName: "skillsSection.skillType1",
    },
    {
        id: 2,
        name: "development",
        translationObjectName: "skillsSection.skillType2",
    },
    {
        id: 3,
        name: "database",
        translationObjectName: "skillsSection.skillType3",
    },
    {
        id: 4,
        name: "devOps",
        translationObjectName: "skillsSection.skillType4",
    },
];

export const technologies = [
    {
        id: 1,
        name: "HTML",
        categoryId: 2,
        iconName: "vscode-icons:file-type-html",
    },
    {
        id: 2,
        name: "CSS",
        categoryId: 2,
        iconName: "vscode-icons:file-type-css",
    },
    {
        id: 3,
        name: "Javascript",
        categoryId: 2,
        iconName: "logos:javascript",
    },
    {
        id: 4,
        name: "Typescript",
        categoryId: 2,
        iconName: "vscode-icons:file-type-typescript-official",
    },
    {
        id: 5,
        name: "ReactJS",
        categoryId: 2,
        iconName: "logos:react",
    },
    {
        id: 6,
        name: "Next.js",
        categoryId: 2,
        iconName: "akar-icons:nextjs-fill",
    },
    {
        id: 7,
        name: "Python",
        categoryId: 2,
        iconName: "logos:python",
    },
    {
        id: 8,
        name: "Java",
        categoryId: 2,
        iconName: "logos:java",
    },
    {
        id: 9,
        name: "NodeJS",
        categoryId: 2,
        iconName: "logos:nodejs-icon",
    },
    {
        id: 10,
        name: "AdonisJS",
        categoryId: 2,
        iconName: "logos:adonisjs-icon",
    },
    {
        id: 11,
        name: "Sass",
        categoryId: 2,
        iconName: "logos:sass",
    },
    {
        id: 12,
        name: "TailwindCSS",
        categoryId: 2,
        iconName: "logos:tailwindcss-icon",
    },
    {
        id: 13,
        name: "Styled components",
        categoryId: 2,
        iconName: "vscode-icons:file-type-styled",
    },
    {
        id: 14,
        name: "ESLint",
        categoryId: 2,
        iconName: "logos:eslint",
    },
    {
        id: 15,
        name: "GraphQL",
        categoryId: 2,
        iconName: "logos:graphql",
    },
    {
        id: 16,
        name: "Jest",
        categoryId: 2,
        iconName: "vscode-icons:file-type-jest",
    },
    {
        id: 17,
        name: "Figma",
        categoryId: 1,
        iconName: "logos:figma",
    },
    {
        id: 18,
        name: "Framer",
        categoryId: 1,
        iconName: "cib:framer",
    },
    {
        id: 19,
        name: "GIMP",
        categoryId: 1,
        iconName: "simple-icons:gimp",
    },
    {
        id: 20,
        name: "MySQL",
        categoryId: 3,
        iconName: "logos:mysql",
    },
    {
        id: 21,
        name: "SQL Server",
        categoryId: 3,
        iconName: "simple-icons:microsoftsqlserver",
    },
    {
        id: 22,
        name: "SQLite",
        categoryId: 3,
        iconName: "logos:sqlite",
    },
    {
        id: 23,
        name: "Jenkins",
        categoryId: 4,
        iconName: "logos:jenkins",
    },
    {
        id: 24,
        name: "Git",
        categoryId: 4,
        iconName: "bi:git",
    },
    {
        id: 25,
        name: "PM2",
        categoryId: 4,
        iconName: "logos:pm2-icon",
    },
    {
        id: 26,
        name: "SkynexUI",
        categoryId: 2,
        iconName: "mdi:alpha-s-box",
    },
    {
        id: 27,
        name: "Supabase",
        categoryId: 2,
        iconName: "logos:supabase-icon",
    },
    {
        id: 28,
        name: "Vercel",
        categoryId: 4,
        iconName: "logos:vercel-icon",
    },
    {
        id: 29,
        name: "React Router",
        categoryId: 2,
        iconName: "logos:react-router",
    },
    {
        id: 30,
        name: "Axios",
        categoryId: 2,
        iconName: "logos:axios",
        size: 20,
    },
];

export const projects: ProjectType[] = [
    {
        id: 1,
        name: "Aluracord",
        slugName: "aluracord",
        role: "fullstack",
        startDate: "01/01/2022",
        endDate: "02/01/2022",
        finished: true,
        imagePath: "/assets/images/aluracord.png",
        imageAlt: "Imagem de um projeto realizado durante o evento 'Imersão React' da Alura chamado Aluracord.",
        descriptionBR: "Projeto realizado durante o evento 'Imersão React' de 2022 feito pela Alura, focado em desenvolver um sistema de comunicação inspirado no Discord, o Aluracord. Ele foi criado utilizando o framework Next.js, SkynexUI (biblioteca para elementos de UI) e Supabase como BaaS (Backend as a Service). Vercel foi usado para a hospedagem do projeto, podendo ser acessado publicamente no link abaixo (seção LINKS).",
        descriptionUS: "Project made during the 2022 'Imersão React' event made by Alura, focused on developing an communication system inspired by Discord, the Aluracord. It was created using the Next.js framework, SkynexUI (library for UI elements) and Supabase as BaaS (Backend as a Service). Vercel was used for project hosting, being able to be accessed publicly in the link below (LINKS section).",
        goalBR: "Reaprender os conceitos básicos do Next.js, agilizar no design do projeto utilizando biblioteca de terceiros para componentes UI, aplicar websocket para criação de um chat em tempo real, autenticar usuários através do Github e consultar a API deles para utilização das imagens de usuário.",
        goalUS: "Relearn the basic concepts of Next.js, speed up the project design using third libraries for UI components, apply websocket for creation of a real time chat, authenticate users through Github and get their API for use of users images.",
        repositoryLink: "https://github.com/erick-menezes/aluracord-game-community",
        appLink: "https://game-community.vercel.app",
        technologyIds: [1, 2, 3, 26, 6, 3, 27, 24, 28, 30],
    },
    {
        id: 2,
        name: "AluraQuiz",
        slugName: "aluraquiz",
        role: "fullstack",
        startDate: "01/01/2021",
        endDate: "01/01/2021",
        finished: false,
        imagePath: "/assets/images/aluraquiz.png",
        imageAlt: "Imagem de um projeto realizado durante a Imersão React da Alura chamado AluraQuiz.",
        descriptionBR: "Projeto realizado durante o evento 'Imersão Next.js' de 2021 feito pela Alura, focado em criar um jogo de quiz web chamado Aluraquiz. Foi desenvolvido usando styled components para estilização e os dados das perguntas/respostas foram armazenados e consumidos em JSON. Vercel foi utilizado na hospedagem da aplicação (link na seção LINKS abaixo).",
        descriptionUS: "Project made during the 2021 'Imersão Next.js' event made by Alura, focused on create a web quiz game called Aluraquiz. Was developed using styled components for stylization and the questions/answers data were stored and consumed in JSON. Vercel was used in the application hosting (link in the LINKS section below).",
        goalBR: "Aprender os conceitos básicos do Next.js, utilizar uma ferramenta 'CSS-in-JS' e entender as vantagens e desvantagens dela, criar a interação do usuário com as perguntas e respostas de forma dinâmica e atrativa.",
        goalUS: "Learn the basic concepts of Next.js, use a 'CSS-in-JS' tool and understand the advantages and disadvantages of it, create an user interaction with the questions and answers dynamically and attractively.",
        repositoryLink: "https://github.com/erick-menezes/imersao_nextjs",
        appLink: "https://gamequiz-alura.vercel.app",
        technologyIds: [1, 2, 3, 6, 13, 14, 24, 28],
    },
    {
        id: 3,
        name: "Eriflix",
        slugName: "eriflix",
        role: "fullstack",
        startDate: "07/01/2020",
        endDate: "05/01/2021",
        finished: false,
        imagePath: "/assets/images/eriflix.png",
        imageAlt: "Imagem de um projeto realizado durante a Imersão React da Alura chamado Eriflix.",
        descriptionBR: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
        descriptionUS: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
        goalBR: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.",
        goalUS: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.",
        repositoryLink: "https://github.com/erick-menezes/eriflix",
        appLink: "https://eriflix.vercel.app",
        technologyIds: [1, 2, 3, 5, 28, 11, 13, 24, 29],
    },
    {
        id: 4,
        name: "Check.it",
        slugName: "check-it",
        role: "fullstack",
        startDate: "06/01/2022",
        endDate: "07/01/2022",
        finished: false,
        imagePath: "/assets/images/check-it.png",
        imageAlt: "Imagem de um projeto pessoal para listagem de compras chamado Check.it.",
        descriptionBR: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
        descriptionUS: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
        goalBR: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.",
        goalUS: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus. Maecenas eget condimentum velit, sit amet feugiat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent auctor purus luctus enim egestas, ac scelerisque ante pulvinar. Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.",
        repositoryLink: "https://github.com/erick-menezes/check.it",
        appLink: "https://check-it-one.vercel.app",
        technologyIds: [1, 2, 6, 13, 4, 17, 24, 28],
    },
];

export const landingMainProjects = [...projects].splice(0, 4);
