import Head from 'next/head';

import { Header } from './components/general/Header/Header';

export default function Home() {
    return (
        <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <p>Testando, 1, 2, 3...</p>
        </div>
    );
}
