import Head from 'next/head';

import { Flex } from '@chakra-ui/react';

import { Header } from './components/general/Header/Header';

export default function Home() {
    return (
        <Flex>
            <Head>
                <title>Erick Menezes Silva - Full Stack Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
        </Flex>
    );
}
